// <auto-generated />
using ClearArch.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ClearArch.Infra.Data.Migrations
{
    [DbContext(typeof(EmployeeDBContext))]
    [Migration("20191020121621_Initais")]
    partial class Initais
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ClearArch.Domain.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Designation");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "Software",
                            FirstName = "Ramzan",
                            LastName = "Khan"
                        },
                        new
                        {
                            Id = 2,
                            Designation = "Doctor",
                            FirstName = "Tariq",
                            LastName = "Khan"
                        },
                        new
                        {
                            Id = 3,
                            Designation = "Teacher",
                            FirstName = "javid",
                            LastName = "Khan"
                        },
                        new
                        {
                            Id = 4,
                            Designation = "Driver",
                            FirstName = "Anaytullah",
                            LastName = "Khan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
